apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-portal
  namespace: stablebridge
  labels:
    app: merchant-portal
    service: merchant-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-portal
  template:
    metadata:
      labels:
        app: merchant-portal
        service: merchant-portal
    spec:
      containers:
        - name: merchant-portal
          image: stablebridge/merchant-portal:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
